services:

  minio:
    image: minio/minio:latest
    container_name: university-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:13
    container_name: university-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore"]
      interval: 5s
      timeout: 5s
      retries: 10

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    restart: unless-stopped

    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      HADOOP_CLASSPATH: "/opt/hadoop/share/hadoop/tools/lib/*"
      SERVICE_OPTS: >-
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "9083:9083"

    volumes:
      - ./jdbc/postgresql-42.7.3.jar:/opt/hive/lib/postgres.jar:ro
      - ./configs/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - hive_warehouse:/opt/hive/data/warehouse
  #hive-server2:
   # image: apache/hive:4.0.0
    #container_name: hive-server2
    #restart: unless-stopped
    #depends_on:
    #  - hive-metastore
    #environment:
    #  SERVICE_NAME: hiveserver2
     # IS_RESUME: "true"
      #HADOOP_CLASSPATH: "/opt/hadoop/share/hadoop/tools/lib/*"
      # Le fix urandom accélère la génération de sessions en Java et évite le gel du bind TCP
      #SERVICE_OPTS: >-
       # -Dhive.metastore.uris=thrift://hive-metastore:9083
        #-Djava.security.egd=file:/dev/./urandom
      #AWS_ACCESS_KEY_ID: minioadmin
      #AWS_SECRET_ACCESS_KEY: minioadmin
    #ports:
     # - "10000:10000"
      #- "10002:10002"
    #volumes:
     # - ./jdbc/postgresql-42.7.3.jar:/opt/hive/lib/postgres.jar:ro
      #- ./configs/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      #- ./configs/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
      # Monte le dossier de JARs pour que HiveServer2 accède au bundle Hudi (crée le dossier ./jars s'il n'existe pas)
      #- ./jars:/opt/hive/auxlib:ro
      #- hive_warehouse:/opt/hive/data/warehouse

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    restart: unless-stopped
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    restart: unless-stopped
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: university-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  metabase:
    image: metabase/metabase:v0.56.6
    container_name: university-metabase
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  airflow-postgres:
    image: postgres:13
    container_name: airflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"

  airflow-init:
    image: apache/airflow:2.10.0-python3.11
    container_name: airflow-init
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    image: apache/airflow:2.10.0-python3.11
    container_name: airflow-webserver
    restart: unless-stopped
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    command: webserver
    ports:
      - "8081:8080"

  airflow-scheduler:
    image: apache/airflow:2.10.0-python3.11
    container_name: airflow-scheduler
    restart: unless-stopped
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    command: scheduler

volumes:
  minio_data:
  postgres_data:
  elasticsearch_data:
  hive_warehouse: