FROM apache/hive:3.1.3

USER root

RUN apt-get update && apt-get install -y curl gettext-base && \
    mkdir -p /opt/hive/auxlib && \
    curl -fsSL -o /opt/hive/auxlib/hudi-hadoop-mr-bundle-0.15.0.jar \
      https://repo1.maven.org/maven2/org/apache/hudi/hudi-hadoop-mr-bundle/0.15.0/hudi-hadoop-mr-bundle-0.15.0.jar && \
    curl -fsSL -o /opt/hive/auxlib/hadoop-aws-3.1.0.jar \
      https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.1.0/hadoop-aws-3.1.0.jar && \
    curl -fsSL -o /opt/hive/auxlib/aws-java-sdk-bundle-1.11.199.jar \
      https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.199/aws-java-sdk-bundle-1.11.199.jar && \
    chmod 644 /opt/hive/auxlib/hudi-hadoop-mr-bundle-0.15.0.jar && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV HIVE_AUX_JARS_PATH=/opt/hive/auxlib

COPY core-site.xml /opt/hadoop/etc/hadoop/core-site.xml
COPY entrypoint-hive-server.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && chown -R hive:hive /opt/hive/conf && chown hive:hive /opt/hadoop/etc/hadoop/core-site.xml && chmod 644 /opt/hadoop/etc/hadoop/core-site.xml

USER hive

ENTRYPOINT ["/entrypoint.sh"]
